Throwing a RuntimeException from go()
RuntimeException caught!
Throwing a RuntimeException from run()
RuntimeException caught!
Tests finished
